// AUTO-GENERATED by scripts/sync-playground.js — do not edit the list by hand.
// Add/rename a component under src/components, then re-run:
//   node scripts/sync-playground.js
import SidebarDemo from "./sidebar";
import ButtonDemo from "./button";
import InputDemo from "./input";
import DropdownDemo from "./dropdown";
import CheckboxDemo from "./checkbox";
import FieldDemo from "./field";
import SearchDemo from "./search";
import TabSwitcherDemo from "./tab-switcher";
import type { DemoEntry } from "./types";

// Each component under src/components is registered here for the gallery list.
export const demos: DemoEntry[] = [
  { name: "sidebar", label: "Sidebar", Demo: SidebarDemo },
  { name: "button", label: "Button", Demo: ButtonDemo },
  { name: "input", label: "Input", Demo: InputDemo },
  { name: "dropdown", label: "Dropdown", Demo: DropdownDemo },
  { name: "checkbox", label: "Checkbox", Demo: CheckboxDemo },
  { name: "field", label: "Field", Demo: FieldDemo },
  { name: "search", label: "Search", Demo: SearchDemo },
  { name: "tab-switcher", label: "Tab Switcher", Demo: TabSwitcherDemo },
];

export type { DemoEntry, DemoProps } from "./types";
