// AUTO-GENERATED by scripts/sync-playground.js — do not edit the list by hand.
// Add/rename a component under src/components, then re-run:
//   node scripts/sync-playground.js
import SidebarDemo from "./sidebar";
import ButtonDemo from "./button";
import InputDemo from "./input";
import DropdownDemo from "./dropdown";
import type { DemoEntry } from "./types";

// Each component under src/components is registered here for the gallery list.
export const demos: DemoEntry[] = [
  { name: "sidebar", label: "Sidebar", Demo: SidebarDemo },
  { name: "button", label: "Button", Demo: ButtonDemo },
  { name: "input", label: "Input", Demo: InputDemo },
  { name: "dropdown", label: "Dropdown", Demo: DropdownDemo },
];

export type { DemoEntry, DemoProps } from "./types";
